"""
stage4_crop.py
--------------
Takes the bounding boxes generated by Stage 3 (Grounding DINO) and crops them into 
context windows. It uses a fixed margin approach to capture the title and dimensions
surrounding the cabinet/countertop without passing the entire 4K page to the LLM.

Usage:
  py stage4_crop.py --pdf_dir "output/(Arch Pdf)_Architectural - 2026-01-16 IFC Eng Copy (2)_pages"
"""

import argparse
import json
import os
from pathlib import Path
from PIL import Image, ImageDraw

# ── Configuration ─────────────────────────────────────────────────────────────

STAGE3_RESULTS = "C:/1stTask/output/stage3_dino/stage3_dino_results.json"
OUTPUT_DIR = "C:/1stTask/output/stage4_crops"

# ── Cropping Logic ────────────────────────────────────────────────────────────

def smart_crop_views(pdf_dir: str):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    if not os.path.exists(STAGE3_RESULTS):
        print(f"Error: {STAGE3_RESULTS} not found. Run stage 3 first.")
        return

    with open(STAGE3_RESULTS, "r", encoding="utf-8") as f:
        results = json.load(f)
        
    for page_data in results:
        page_name = page_data["filename"]
        img_path = os.path.join(pdf_dir, page_name)
        
        if not os.path.exists(img_path):
            continue
            
        print(f"Processing {page_name}...")
        
        # We need a clean image for cropping, and a vis image for the full-page overview.
        # This prevents the blue context windows from bleeding into adjacent crops.
        try:
            orig_img = Image.open(img_path).convert("RGB")
        except Exception as e:
            print(f"  [ERROR] Cannot open image: {e}")
            continue
            
        vis_img = orig_img.copy()
        draw_vis = ImageDraw.Draw(vis_img)
        
        crop_idx = 0
        for cand in page_data.get("objects", []):
            box = cand["box"]
            x1, y1, x2, y2 = box
            
            # ─────────────────────────────────────────────────────────
            # CONTEXT WINDOW MARGIN
            # We guarantee exactly 600 pixels of margin on all sides to 
            # capture titles and dimensions, which fits perfectly into 
            # Qwen's VRAM constraints without crashing.
            # ─────────────────────────────────────────────────────────
            MARGIN = 600
            
            bx = max(0, int(x1 - MARGIN))
            by = max(0, int(y1 - MARGIN))
            bx2 = min(orig_img.width, int(x2 + MARGIN))
            by2 = min(orig_img.height, int(y2 + MARGIN))
            
            # Draw blue context box ONLY on the full-page visualization
            draw_vis.rectangle([bx, by, bx2, by2], outline="blue", width=10)
            draw_vis.rectangle([x1, y1, x2, y2], outline="red", width=4)
            
            # Crop from the CLEAN original image
            crop_img = orig_img.crop((bx, by, bx2, by2))
            
            crop_path = os.path.join(OUTPUT_DIR, f"{page_name}_crop{crop_idx}.png")
            crop_img.save(crop_path)
            print(f"  Saved clean crop: {crop_path}")
            crop_idx += 1
                
        # Save visualization
        vis_path = os.path.join(OUTPUT_DIR, f"{page_name}_vis.png")
        vis_img.save(vis_path)
        print(f"  Saved visualization: {vis_path}")

# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run Stage 4 View Cropping")
    parser.add_argument("--pdf_dir", type=str, required=True, help="Path to the folder of extracted PDF pages")
    args = parser.parse_args()
    
    smart_crop_views(args.pdf_dir)
