import gradio as gr
import os
import json
import glob
import shutil
import time
import zipfile

# Import backend modules
import pipeline
import validator

# ====================================================
# GLOBAL STATE & INITIALIZATION
# ====================================================

def load_all_rules():
    """Loads all rule JSONs from the rules/ directory."""
    rule_files = glob.glob(os.path.join("rules", "*.json"))
    rules = []
    for rf in rule_files:
        try:
            with open(rf, 'r', encoding='utf-8') as f:
                data = json.load(f)
                if isinstance(data, list):
                    rules.extend(data)
                else:
                    rules.append(data)
        except Exception as e:
            print(f"Error loading rule {rf}: {e}")
    return rules

GLOBAL_RULES = load_all_rules()


# ====================================================
# CORE FUNCTIONS
# ====================================================

def process_pdfs(sub_pdf_path, arch_pdf_path, progress=gr.Progress()):
    """Stage 1: Runs the pipeline crop step and extracts metadata."""
    if not sub_pdf_path:
        raise gr.Error("Please upload a Submittal PDF.")
        
    pdf_basename = os.path.splitext(os.path.basename(sub_pdf_path))[0]
    
    # 1. Clear old crop directories for this basename to ensure session isolation
    sub_crop_dir = os.path.join("Submittal_crop", pdf_basename)
    if os.path.exists(sub_crop_dir):
        shutil.rmtree(sub_crop_dir)
        
    # We do not clear Arch_crop fully because it's shared/indexed, but it overwrites.
    
    progress(0.2, desc="Running crop pipeline (this may take a few minutes)...")
    
    # 2. Run Pipeline (Crop & Metadata Extraction)
    if arch_pdf_path is None:
        # Pass a dummy string or rely on the pipeline's failure handling.
        pass
        
    pipeline.run_full_pipeline(sub_pdf_path, arch_pdf_path)
    
    progress(0.8, desc="Loading metadata...")
    
    # 3. Read Metadata generated by pipeline.py
    meta_file = f"submittal_metadata_{pdf_basename}.json"
    if not os.path.exists(meta_file):
        raise gr.Error(f"Failed to generate metadata. Could not find {meta_file}.")
        
    with open(meta_file, 'r', encoding='utf-8') as f:
        metadata = json.load(f)
        
    # Map source_file -> metadata
    crop_map = {os.path.normpath(m.get("source_file")): m for m in metadata if m.get("source_file")}
    
    # Extract choices (the crop paths)
    choices = list(crop_map.keys())
    
    progress(1.0, desc="Complete!")
    return crop_map, gr.update(choices=choices, value=None), "✅ Cropping complete. Please select an image."


def on_image_select(selected_image, crop_map, results_state):
    """Updates the UI when a user selects a cropped image."""
    if not selected_image:
        return gr.update(choices=[]), None, []
        
    meta = crop_map.get(os.path.normpath(selected_image), {})
    view_type = str(meta.get("view_type", "")).upper()
    view_name = str(meta.get("view_name", "")).upper()
    
    # Filter rules based on view_type or view_name
    applicable_rules = []
    for r in GLOBAL_RULES:
        views_to_check = [v.upper() for v in r.get("views_need_to_check", [])]
        if view_type in views_to_check or view_name in views_to_check:
            applicable_rules.append(r)
        else:
            # Fallback partial matching
            for rv in views_to_check:
                if view_name.startswith(rv):
                    applicable_rules.append(r)
                    break
                    
    # Format for Dropdown: (Display Name, Value)
    rule_choices = [(f"{r.get('rule_id')} - {r.get('rule_name', 'Unnamed')}", r.get("rule_id")) for r in applicable_rules]
    
    # Filter results table to ONLY show results for the currently selected view
    filtered_results = [res for res in results_state if res["source_file"] == selected_image]
    
    # Table data format
    table_data = [
        [r["rule_id"], r["rule_name"], r.get("view_id", "Unknown"), r["view_name"], r["view_type"], r["status"], r["confidence"], r["reasoning"]] 
        for r in filtered_results
    ]
    
    # Determine which image to show in Visualizer
    display_image = selected_image
    # If there's a markup image from the latest validation run on this view, show it
    for r in reversed(filtered_results):
        if r.get("markup_img_path") and os.path.exists(r["markup_img_path"]):
            display_image = r["markup_img_path"]
            break
            
    return gr.update(choices=rule_choices, value=None), display_image, table_data


def apply_validation(selected_rules, selected_image, crop_map, results_state, progress=gr.Progress()):
    """Stage 2: Runs validator on selected rule(s) for the selected image."""
    if not selected_image:
        raise gr.Error("Please select an image first.")
    if not selected_rules:
        raise gr.Error("Please select at least one rule to validate.")
        
    # Ensure selected_rules is a list
    if not isinstance(selected_rules, list):
        selected_rules = [selected_rules]
        
    meta = crop_map.get(os.path.normpath(selected_image), {})
    arch_ref = meta.get("arch_ref", "NA")
    
    # Construct expected arch_crop_path
    arch_crop_path = "NA"
    if arch_ref and arch_ref != "NA" and "/" in arch_ref:
        parts = arch_ref.split("/")
        dr_num = parts[0].strip()
        sh_name = parts[1].strip()
        expected_arch_crop = os.path.join("Arch_crop", sh_name, f"{sh_name}_{dr_num}.png")
        if os.path.exists(expected_arch_crop):
            arch_crop_path = expected_arch_crop
            
    # Session output directory for this run
    session_id = str(int(time.time()))
    output_dir = os.path.join("results_ui", session_id)
    os.makedirs(output_dir, exist_ok=True)
    
    # Run validation for each selected rule
    for idx, rule_id in enumerate(selected_rules):
        rule = next((r for r in GLOBAL_RULES if r.get("rule_id") == rule_id), None)
        if not rule:
            print(f"Rule {rule_id} not found. Skipping.")
            continue
            
        progress((idx) / len(selected_rules), desc=f"Validating Rule: {rule_id}...")
        
        req_sources = [r.lower() for r in rule.get("required_sources", [])]
        requires_arch = any("arch" in r or "architectural drawing" in r for r in req_sources)
        
        # Call the backend validator
        if requires_arch:
            validator.run_pipeline(selected_image, arch_crop_path, rule, output_dir, arch_ref)
        else:
            import submittal
            submittal.run_pipeline_single_rule(selected_image, rule, output_dir, cached_views=None)
            
        sub_base = os.path.splitext(os.path.basename(selected_image))[0]
        rule_base = rule.get("rule_id", "UnknownRule")
        
        result_json_path = os.path.join(output_dir, f"{rule_base}_{sub_base}_result.json")
        markup_img_path = os.path.join(output_dir, f"{rule_base}_{sub_base}_markup.jpg")
        markup_pdf_path = os.path.join(output_dir, f"{rule_base}_{sub_base}_markup.pdf")
        
        # Parse result
        new_result = {
            "source_file": selected_image,
            "rule_id": rule_base,
            "rule_name": rule.get("rule_name", "Unknown Rule"),
            "view_id": "Unknown",
            "view_name": meta.get("view_name", "Unknown"),
            "view_type": meta.get("view_type", "Unknown"),
            "status": "ERROR",
            "confidence": 0.0,
            "reasoning": "Failed to run or no output.",
            "markup_img_path": markup_img_path if os.path.exists(markup_img_path) else None,
            "json_path": result_json_path if os.path.exists(result_json_path) else None,
            "pdf_path": markup_pdf_path if os.path.exists(markup_pdf_path) else None
        }
        
        if os.path.exists(result_json_path):
            try:
                with open(result_json_path, 'r', encoding='utf-8') as f:
                    res_data = json.load(f)
                    new_result["status"] = res_data.get("sheet_status", "UNKNOWN")
                    vr = res_data.get("view_results", [{}])[0]
                    new_result["view_id"] = vr.get("view_id", "Unknown")
                    new_result["confidence"] = vr.get("confidence_score", 0.0)
                    new_result["reasoning"] = vr.get("reasoning", "")
            except Exception as e:
                new_result["reasoning"] = f"Error parsing result: {e}"
                
        results_state.append(new_result)
        
    progress(1.0, desc="Validation Complete!")
    
    # Refresh the UI for the currently selected image
    _, display_image, table_data = on_image_select(selected_image, crop_map, results_state)
    return results_state, display_image, table_data


# ====================================================
# DOWNLOAD HANDLERS (Filtered to Current View)
# ====================================================

def create_zip_for_view(selected_image, results_state, file_key, zip_name):
    """Generic helper to zip files of a certain type for the selected view."""
    filtered = [r for r in results_state if r["source_file"] == selected_image]
    if not filtered:
        raise gr.Error("No results found for the selected view.")
        
    paths_to_zip = [r[file_key] for r in filtered if r.get(file_key)]
    if not paths_to_zip:
        raise gr.Error(f"No {file_key.replace('_path', '')} files generated for this view.")
        
    os.makedirs("results_ui", exist_ok=True)
    zip_path = os.path.join("results_ui", zip_name)
    
    with zipfile.ZipFile(zip_path, 'w') as zipf:
        for p in paths_to_zip:
            # Avoid storing absolute paths in zip
            zipf.write(p, os.path.basename(p))
            
    return zip_path

def download_json(selected_image, results_state, format_choice):
    if format_choice == "Zip":
        return create_zip_for_view(selected_image, results_state, "json_path", "results_json.zip")
    else:
        # Merged JSON
        filtered = [r for r in results_state if r["source_file"] == selected_image]
        if not filtered:
            raise gr.Error("No results found for the selected view.")
            
        merged_data = []
        for r in filtered:
            if r.get("json_path") and os.path.exists(r["json_path"]):
                with open(r["json_path"], 'r') as f:
                    merged_data.append(json.load(f))
                    
        os.makedirs("results_ui", exist_ok=True)
        merged_path = os.path.join("results_ui", "merged_results.json")
        with open(merged_path, 'w', encoding='utf-8') as f:
            json.dump(merged_data, f, indent=2)
            
        return merged_path

def download_images(selected_image, results_state):
    return create_zip_for_view(selected_image, results_state, "markup_img_path", "markup_images.zip")

def download_pdfs(selected_image, results_state):
    return create_zip_for_view(selected_image, results_state, "pdf_path", "markup_pdfs.zip")




# ====================================================
# GRADIO UI LAYOUT & THEME
# ====================================================

custom_css = """
/* Header */
.app-header {
    display: flex;
    align-items: center;
    padding: 16px 0px;
}
.app-header h1 {
    margin: 0;
    font-size: 24px;
    font-weight: 700;
    color: #F8FAFC;
    display: flex;
    align-items: center;
    gap: 12px;
}

/* Headings */
h3 {
    font-size: 16px !important;
    font-weight: 600 !important;
    margin-bottom: 12px !important;
    color: #F8FAFC !important;
}
h4 {
    font-size: 14px !important;
    color: #94A3B8 !important;
    margin-bottom: 8px !important;
    margin-top: 16px !important;
}

/* Make image background white */
.viewer-box img {
    background-color: #ffffff !important;
}

/* Table Hover and Layout Fix */
.dataframe tr:hover td, .dataframe tr:hover th {
    background-color: #1F2937 !important;
    color: #F8FAFC !important;
}
.dataframe th {
    white-space: nowrap !important;
    min-width: 80px !important;
}
.dataframe td {
    word-break: break-word !important;
    white-space: normal !important;
}
"""

my_theme = gr.themes.Base(
    primary_hue="blue",
    neutral_hue="slate",
    font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "system-ui", "sans-serif"],
).set(
    body_background_fill="#0B0F19",
    body_text_color="#F8FAFC",
    
    background_fill_primary="#111827",
    background_fill_secondary="#1F2937",
    
    border_color_primary="#1F2937",
    border_color_accent="#3B82F6",
    
    block_background_fill="#111827",
    block_border_width="1px",
    block_border_color="#1F2937",
    
    block_label_background_fill="#111827",
    block_label_text_color="#94A3B8",
    block_title_text_color="#F8FAFC",
    block_title_text_weight="600",
    
    button_primary_background_fill="#2563EB",
    button_primary_background_fill_hover="#1D4ED8",
    button_primary_text_color="#F8FAFC",
    
    button_secondary_background_fill="#1F2937",
    button_secondary_background_fill_hover="#374151",
    button_secondary_text_color="#F8FAFC",
    button_secondary_border_color="#374151",
    
    panel_background_fill="#111827",
    input_background_fill="#1F2937",
    input_border_color="#374151",
    
    checkbox_background_color="#1F2937",
    table_odd_background_fill="#111827",
    table_even_background_fill="#111827",
)

with gr.Blocks(title="QC finish_byothers", theme=my_theme, css=custom_css) as demo:
    
    # State variables
    crop_map_state = gr.State({})
    results_state = gr.State([])
    
    # Header
    gr.HTML("""
    <div class="app-header">
        <h1>✨ QC finish_byothers - Millwork CAD QC Automation</h1>
    </div>
    """)
    
    with gr.Row():
        
        # ------------------------------------------------
        # COLUMN 1: LEFT CONTROLS
        # ------------------------------------------------
        with gr.Column(scale=1, min_width=280):
            
            gr.Markdown("### Upload & Crop")
            
            with gr.Group():
                sub_pdf = gr.File(label="Submittal PDF", file_types=[".pdf"])
                arch_pdf = gr.File(label="Arch PDF", file_types=[".pdf"])
                
            process_btn = gr.Button("Process (Crop Views)", variant="primary")
            
            gr.Markdown("#### Status")
            with gr.Group():
                status_text = gr.Markdown("Ready.")
            
            gr.Markdown("### Select & Validate")
            
            with gr.Group():
                image_dropdown = gr.Dropdown(label="Image Selection", choices=[], interactive=True)
                rule_dropdown = gr.CheckboxGroup(label="Rule Selection", choices=[], interactive=True)
                
            validate_btn = gr.Button("Apply Validation", variant="primary")
            
            gr.Markdown("### Downloads")
            with gr.Group():
                json_format = gr.Radio(label="Data Format", choices=["Merged JSON", "Zip"], value="Merged JSON")
                dl_json_btn = gr.Button("Export JSON Results", variant="secondary")
                dl_json_file = gr.File(label="JSON Result", visible=True)
                
                dl_pdf_btn = gr.Button("Export Markup PDFs", variant="secondary")
                dl_pdf_file = gr.File(label="PDF Result", visible=True)
                
                dl_img_btn = gr.Button("Export Markup Images", variant="secondary")
                dl_img_file = gr.File(label="Image Result", visible=True)
            
        # ------------------------------------------------
        # COLUMN 2: VISUALIZER
        # ------------------------------------------------
        with gr.Column(scale=3):
            
            gr.Markdown("### Visualizer")
            with gr.Group(elem_classes="viewer-box"):
                visualizer = gr.Image(label="Selected View", type="filepath", interactive=False, show_label=True, height="75vh")

        # ------------------------------------------------
        # COLUMN 3: RESULTS
        # ------------------------------------------------
        with gr.Column(scale=3):
            
            gr.Markdown("### Results")
            results_table = gr.Dataframe(
                headers=["Rule ID", "Rule Name", "View ID", "View Name", "View Type", "Status", "Confidence", "Reasoning"],
                datatype=["str", "str", "str", "str", "str", "str", "number", "str"],
                column_widths=["15%", "15%", "15%", "15%", "15%", "15%", "20%", "30%"],
                interactive=False,
                wrap=True,
            )


    # ====================================================
    # EVENT WIRING
    # ====================================================
    
    # 1. Process Button -> Crop & Metadata
    process_btn.click(
        fn=process_pdfs,
        inputs=[sub_pdf, arch_pdf],
        outputs=[crop_map_state, image_dropdown, status_text]
    )
    
    # 2. Image Selection -> Update Visualizer, Rules, and Table
    image_dropdown.change(
        fn=on_image_select,
        inputs=[image_dropdown, crop_map_state, results_state],
        outputs=[rule_dropdown, visualizer, results_table]
    )
    
    # 3. Apply Validation -> Run Validator & Update UI
    validate_btn.click(
        fn=apply_validation,
        inputs=[rule_dropdown, image_dropdown, crop_map_state, results_state],
        outputs=[results_state, visualizer, results_table]
    )
    
    # 4. Downloads
    dl_json_btn.click(
        fn=download_json,
        inputs=[image_dropdown, results_state, json_format],
        outputs=[dl_json_file]
    )
    
    dl_img_btn.click(
        fn=download_images,
        inputs=[image_dropdown, results_state],
        outputs=[dl_img_file]
    )
    
    dl_pdf_btn.click(
        fn=download_pdfs,
        inputs=[image_dropdown, results_state],
        outputs=[dl_pdf_file]
    )

# Launch
if __name__ == "__main__":
    demo.launch(max_file_size="500mb")
