import os
import sys
import glob
import json
import subprocess

def main():
    if len(sys.argv) < 3:
        print("Usage: python src/run_batch.py <Submittal_PDF_Name> <Arch_PDF_Name> [other main.py arguments...]")
        print("Example: python src/run_batch.py Submittal_25092 Arch_Rev2 Sink_and_faucet.json schedule_DGS.xlsx --target-tag \"PF-4\"")
        sys.exit(1)

    submittal_pdf_name = sys.argv[1]
    arch_pdf_name = sys.argv[2]
    main_args = sys.argv[3:]

    # Locate the meta_data_json directory
    base_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(base_dir)
    json_dir = os.path.join(project_root, "meta_data_json", submittal_pdf_name)

    if not os.path.exists(json_dir):
        print(f"Error: Could not find JSON directory at {json_dir}")
        print("Make sure you have run crop.py on this Submittal PDF first.")
        sys.exit(1)

    # Find all JSON files generated by crop.py for this submittal
    json_files = glob.glob(os.path.join(json_dir, "**", "*.json"), recursive=True)
    
    if not json_files:
        print(f"No JSON files found in {json_dir}")
        sys.exit(1)

    print(f"Found {len(json_files)} metadata JSON file(s). Processing...")

    total_runs = 0
    failed_runs = 0

    for json_path in json_files:
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                views = json.load(f)
        except Exception as e:
            print(f"Error reading {json_path}: {e}")
            continue

        for view in views:
            source_file = view.get("source_file")
            if not source_file:
                continue

            print("\n" + "="*80)
            print(f"Executing AI Pipeline for View: {view.get('view_name', 'Unknown')}")
            print(f"Source File: {source_file}")
            print("="*80)

            # Build the command simulating the UI
            cmd = [
                sys.executable,
                os.path.join("src", "main.py"),
                json_path,
            ] + main_args + [
                "--arch-pdf-name", arch_pdf_name,
                "--target-source-file", source_file
            ]

            # Run it
            try:
                result = subprocess.run(cmd, cwd=project_root)
                if result.returncode != 0:
                    print(f"❌ Pipeline failed for {source_file} (Exit code {result.returncode})")
                    failed_runs += 1
                else:
                    print(f"✅ Successfully finished {source_file}")
            except Exception as e:
                print(f"❌ Exception running pipeline for {source_file}: {e}")
                failed_runs += 1
                
            total_runs += 1

    print("\n" + "="*80)
    print("Batch Processing Complete!")
    print(f"Total Views Processed: {total_runs}")
    print(f"Failed Runs: {failed_runs}")
    print("="*80)

if __name__ == "__main__":
    main()
